[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "adeilink"
version = "0.0.1"
description = "A library to load data from ADEI services."
authors = [
    { name = "Suren A. Chilingaryan", email = "csa@suren.me" },
]
